FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# COPY .next/standalone ./
# COPY .next/static ./.next/static
# COPY public ./public  

EXPOSE 3030
CMD ["npm", "run", "start"]